import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { QueryProvider } from 'feature/query/QueryProvider';
import { Toaster } from 'react-hot-toast';
import Footer from 'feature/landing/components/primitives/Footer';
import Header from 'feature/landing/components/primitives/Header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F0F0F0]`}
      >
        <div>
          <Header />
          <div className="min-h-screen">
            <QueryProvider>{children}</QueryProvider>
            <Toaster position="top-right" />
          </div>
          <div className="flex flex-1">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
